### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by brettalton** [ebeigarts/homebrew-magic-lantern#1]
I wasn't able to get this working, Mac 10.12.1 High Sierra, Xcode Command Line tools installed.

```
$ brew tap ebeigarts/homebrew-magic-lantern
==> Tapping ebeigarts/magic-lantern
Cloning into '/usr/local/Homebrew/Library/Taps/ebeigarts/homebrew-magic-lantern'...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ebeigarts/homebrew-magic-lantern/magic_lantern_formula.rb
formulae require at least a URL
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ebeigarts/homebrew-magic-lantern/magic_lantern_download_strategy.rb
wrong number of arguments (given 4, expected 2)
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ebeigarts/homebrew-magic-lantern/raw2dng.rb
Calling Resource#sha1 is disabled!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/ebeigarts/homebrew-magic-lantern/magic_lantern_formula.rb:15:in `block (2 levels) in inherited'
Please report this to the ebeigarts/magic-lantern tap!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ebeigarts/homebrew-magic-lantern/cr2hdr.rb
Calling Resource#sha1 is disabled!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/ebeigarts/homebrew-magic-lantern/magic_lantern_formula.rb:15:in `block (2 levels) in inherited'
Please report this to the ebeigarts/magic-lantern tap!
Error: Cannot tap ebeigarts/magic-lantern: invalid syntax in tap!
```

**Comment by ebeigarts** [comment]
@brettalton haven't used this for years, it seems to be broken and I'm not interested in fixing this right now, sorry
